demomvc/Controllers/DemoController.cs
using Microsoft.AspNetCore.Mvc;

namespace demomvc.Controllers;

    public class DemoController : Controller
    {
        // khai bao cac phuong thuc
        public IActionResult Index(){
            return View();
        }
        [HttpPost]
        public IActionResult Index(string fName, string dieu)
        {
            string strResult = "Xin chao" + fName + "-" + dieu;
            ViewBag.xcv = strResult;
            return View();
    }
    
}

demomvc/Controllers/LuongController.cs
namespace demoMvc.Controllers;
using Microsoft.AspNetCore.Mvc;
using demoMvc.Models;
public class LuongController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Sum(TinhLuong tl)
    {

        tl.TongLuong = tl.LuongCoBan * tl.HeSoLuong + tl.PhuCap;
        ViewBag.A="Luong=" +tl.TongLuong;
        return View("Index",tl);

    }
}

demomvc/Controllers/PersonController.cs
using Microsoft.AspNetCore.Mvc;
using demomvc.Models;
using Microsoft.EntityFrameworkCore; 
using demomvc.Data;
using demomvc.Models.Process;
using OfficeOpenXml;
using X.PagedList;
using Microsoft.AspNetCore.Mvc.Rendering;
namespace demomvc.Controllers
{
    public class PersonController : Controller

    {
        private readonly ApplicationDbContext _context;
        public PersonController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(int? page, int? pageSize)
        {
            ViewBag.pageSize =new List<SelectListItem>()
            {
                new SelectListItem() { Value="3", Text= "3"},
                new SelectListItem() { Value="5", Text= "5"},
                new SelectListItem() { Value="10", Text= "10"},
                new SelectListItem() { Value="15", Text= "15"},
                new SelectListItem() { Value="25", Text= "25"},
                new SelectListItem() { Value="50", Text= "50"},
            };
            int pagesize =(pageSize ?? 3);
            ViewBag.psize = pageSize;

            var model = _context.Person.ToList().ToPagedList(page ?? 1, pagesize);
            return View(model);
        }
          private ExcelProcess _excelPro = new ExcelProcess();
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PersonID,FullName, Address")] Person person)
        {
            if (ModelState.IsValid)
            {
                _context.Add(person);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(person);
        }
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Person == null)
            {
                return NotFound();
            }

            var person = await _context.Person.FindAsync(id);
            if (person == null)
            {
                return NotFound();
            }
            return View(person);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("PersonID,FullName, Address")] Person person)
        {
            if (id != person.PersonID)
            {
                return NotFound();
            }
              if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(person);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonExists(person.PersonID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(person);
        }
        public async Task<IActionResult> Delete(string id)
        {
            
            if (id == null || _context.Person == null)
            {
                return NotFound();
            }

            var person = await _context.Person.FirstOrDefaultAsync(m => m.PersonID == id);
            if (person == null)
            {
                return NotFound();
            }
            return View(person);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Person == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Person' is null.");
            }

            var person = await _context.Person.FindAsync(id);
            if (person != null)
            {
                _context.Person.Remove(person);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        private bool PersonExists(string id)
        {
            return (_context.Person?.Any(e =>e.PersonID == id)).GetValueOrDefault();
        }
    
        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile file)
        {
            if (file!=null)
                {
                    string fileExtension = Path.GetExtension(file.FileName);
                    if (fileExtension != ".xls" && fileExtension != ".xlsx")
                    {
                        ModelState.AddModelError("", "Please choose excel file to upload!");
                    }
                    else
                    {
                        //rename file when upload to server
                        var filePath = Path.Combine(Directory.GetCurrentDirectory() + "/Uploads/Excels", "File" + DateTime.Now.Day + DateTime.Now.Hour + DateTime.Now.Minute + DateTime.Now.Millisecond + fileExtension);
                        var fileLocation = new FileInfo(filePath).ToString();
                        if (file.Length > 0)
                        {
                            using (var stream = new FileStream(filePath, FileMode.Create))
                            {
                                //save file to server
                                await file.CopyToAsync(stream);
                                //read data from file and write to database
                                var dt = _excelPro.ExcelToDataTable(fileLocation);
                                for(int i = 0; i < dt.Rows.Count; i++)
                                {
                                    var ps = new Person();
                                    ps.PersonID = dt.Rows[i][0].ToString();
                                    ps.FullName = dt.Rows[i][1].ToString();
                                    ps.Address = dt.Rows[i][2].ToString();
                                    _context.Add(ps);
                                }
                                await _context.SaveChangesAsync();
                                return RedirectToAction(nameof(Index));
                            }
                        }
                    }
                }
            
            return View();
        }  
        public IActionResult Download()
        {
            var fileName = "PersonList.xlsx";
            using(ExcelPackage excelPackage = new ExcelPackage())
            {
                ExcelWorksheet excelWorksheet = excelPackage.Workbook.Worksheets.Add("Sheet 1");
                excelWorksheet.Cells["A1"].Value = "PersonID";
                excelWorksheet.Cells["B1"].Value = "FullName";
                excelWorksheet.Cells["C1"].Value = "Address";
                var psList = _context.Person.ToList();
                excelWorksheet.Cells["A2"].LoadFromCollection(psList);
                var stream = new MemoryStream(excelPackage.GetAsByteArray());
                return File(stream,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",fileName);
            }
        } 


    }
}


  

demomvc/Controllers/giaiptbac2Controller.cs
using Microsoft.AspNetCore.Mvc;
namespace demoMvc.Controllers;
using demomvc.Models;
public class giaiptbac2Controller : Controller
{
    public ActionResult Index()
    {
        return View();
    }
    [HttpPost]
    public ActionResult Solve(DIEU2K2 Dieu)
    {
        if (Dieu.A == 0)
        {
            ViewBag.D = "A phai khac 0.";
            return View("Index", Dieu);
        }

        Dieu.Delta = Dieu.B * Dieu.B - 4 * Dieu.A * Dieu.C;
        ViewBag.A = "delta= " + Dieu.Delta;
        if (Dieu.Delta < 0)
        {
            ViewBag.B = "Phuong trinh khong vo nghiem.";
        }
        else if (Dieu.Delta == 0)
        {
            Dieu.X1 = -Dieu.B / (2 * Dieu.A);
            ViewBag.C = "Phuong trinh co nghiem kep: X1=X2=" + Dieu.X1;
        }
        else
        {
            Dieu.X1 = (-Dieu.B + Math.Sqrt(Dieu.Delta)) / (2 * Dieu.A);
            Dieu.X2 = (-Dieu.B - Math.Sqrt(Dieu.Delta)) / (2 * Dieu.A);
            ViewBag.D = "Phuong trinh co 2 nghiem: " + " X1= " + Dieu.X1 + " ; " + "X2 = " + Dieu.X2;
        }


        return View("Index", Dieu);
    }
}

demomvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - demomvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/demomvc.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">demomvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Demo" asp-action="Index">an vao day di</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="giaiptbac2" asp-action="Index">giaiptbac2</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Luong" asp-action="Index">Luong</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="Index">Person</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - demomvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>